### ISSUE TITLE
Compile to es5

### ISSUE THREAD

**Issue by chrisjaure** [alcidesqueiroz/power-range#1]
Hey! Nice lib. I'm using it in the browser with create-react-app, and I'm running into a build issue due to Uglify not supporting es6 and your use of the fat arrow syntax. Would it be possible to either use only es5 or add a compilation step before publishing to npm?

I'd be happy to submit a PR if you have an opinion either way.

**Comment by alcidesqueiroz** [comment]
Hi, @chrisjaure. Sorry it took me so long to reply. 

Originally, I was addressing Node as my target platform, but I think there's no problem with including a transpiled distributable version.    

About your suggestions: I'm not a fan of the first option, since ES2015+ is already widely used, mature enough and future-proof. So, going back to ES5 is not a good idea for me.
Probably, the best solution would be to have a simple build step with Babel to transpile source back to ES5. As the project consists of a single module, Babel would do the job alone (no need for a bundler, like Browserify). 

Well, unfortunately, I won't be able to work on this improvement during the next days (at least until next  Thursday), due to some approaching deadlines of projects I'm working on. If you have interest in contributing, feel free to open a PR.

**Comment by chrisjaure** [comment]
Hey @alcidesqueiroz, no problem. I can take a stab at it.

**Comment by alcidesqueiroz** [comment]
@chrisjaure 
After merging your PR and released v1.0.2 I noticed some problems in the browser build:
1) All functions and variables were exposed globally
2) It was using commonJS exporting instead of UMD
3) type-detect (a dependency of power-range) hasn't a browser version

When I have free time, I will work on a solution for this problem, maybe by using [transform-es2015-modules-umd](https://babeljs.io/docs/plugins/transform-es2015-modules-umd). For now, I released v1.0.3, which is identical to v1.0.1.

If you have some suggestion, let me know.

**Comment by chrisjaure** [comment]
Hey @alcidesqueiroz, I can confirm that v1.0.2 works perfectly.

Perhaps I didn't explain my original problem well. I wasn't looking for a UMD build. Since I'm using webpack, a commonJS module is exactly what I want. The only thing I needed to be fixed was es2016 -> es5 compilation. This allows your package to be used in the browser with webpack or browserify.

**Comment by alcidesqueiroz** [comment]
I get it, @chrisjaure. Well, I think UMD would be an even better solution, because it addresses more usage scenarios, including yours (since it's commonJS-compatible), am I right? If so, in the next release I'll fix the issues I enumerated above and release an UMD browser version. In this meanwhile, you can lock the reference in your project to the v1.0.2, which works for you.
